### PR TITLE
Fix build of boost::iostreams zlib filter

### LINKED ISSUE #122: Latest builds do not have zlib enabled
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The latest builds do not have zlib enabled.
For example https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/489010/logs/27
shows zlib: no.
The linux-64/boost-cpp-1.77.0-he72f1d9_2.tar.bz2 build published 10 days ago is broken, whereas the linux-64/boost-cpp-1.77.0-h359cf19_1.tar.bz2 build published many months earlier is OK.

It appears that the previous fix for this, https://github.com/conda-forge/boost-cpp-feedstock/issues/114 & https://github.com/conda-forge/boost-cpp-feedstock/pull/115 by @benmwebb, was not actually merged into `main` - it was just merged into a version branch.

### Installed packages

```shell
conda list
```

### Environment info

```shell
conda info
```

### PR DESCRIPTION
**Pull request by benmwebb**
Explicitly add zlib to the requirements so that boost::iostreams gets built with the zlib filter. This was being pulled in implicitly at one point but recently stopped working; make it explicit. Add a compile+link test to make sure the final
library includes the necessary symbols. Closes #122.

This is essentially the same as PR #115 (which fixed the issue for the 1.74.x branch) but for the main branch.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

File: recipe/run_test.sh [hunk 1]
```diff
@@ -0,0 +1,8 @@
+# Skip compile tests if we are cross-compiling
+if [[ "${build_platform}" != "${target_platform}" ]]; then
+  exit 0
+fi
+
+# Test boost::iostreams zlib filter support
+cd test
+${CXX} -I$PREFIX/include -L$PREFIX/lib test_iostreams_zlib.cpp -lboost_iostreams
```
Comment (jakirkham) [inline recipe/run_test.sh:8]: Forget whether we need to run these scripts ourselves when using `test/commands` or not. Did these get run in the previous change? It's not clear from the logs.

File: recipe/run_test.sh [hunk 2]
```diff
@@ -0,0 +1,8 @@
+# Skip compile tests if we are cross-compiling
```
Comment (jakirkham) [inline recipe/run_test.sh:1]: Maybe we should pass some flags to `bash` to get these commands to show up?

File: recipe/test/test_iostreams_zlib.cpp [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+
+int main()
+{
+    using namespace std;
+
+    ifstream file("hello.z", ios_base::in | ios_base::binary);
+    boost::iostreams::filtering_streambuf<boost::iostreams::input> in;
+    in.push(boost::iostreams::zlib_decompressor());
+    in.push(file);
+    boost::iostreams::copy(in, cout);
```
Comment (jakirkham) [inline recipe/test/test_iostreams_zlib.cpp:17]: Maybe it is worth printing some output just to know what is happening in the logs (and help diagnose any issues if they arise)?

File: recipe/run_test.bat [hunk 4]
```diff
@@ -0,0 +1,4 @@
+:: Test boost::iostreams zlib filter support
```
Comment (jakirkham) [inline recipe/run_test.bat:1]: Same as with `bash`, it might be worth echoing command lines run (and any output) to make sure things are running ok.

**Review by jakirkham — COMMENTED** [review]
Thanks Ben! 😄

Had a couple questions below around testing

File: recipe/run_test.sh (hunk 1 above)
Comment (benmwebb) [reply recipe/run_test.sh:8]: Yes, `run_test.{sh,bat}` gets run in addition to anything else you have in the `meta.yaml's` `test` block. (At least, it definitely ran with the previous PR, because it failed for my first attempt on cross-compile archs.)

File: recipe/test/test_iostreams_zlib.cpp (hunk 3 above)
Comment (benmwebb) [reply recipe/test/test_iostreams_zlib.cpp:17]: We only compile and link this program - we don't actually run it. So you wouldn't see any prints anyway.

Comment (jakirkham) [reply recipe/test/test_iostreams_zlib.cpp:17]: Ah ok. Should we try running it then?

Comment (benmwebb) [reply recipe/test/test_iostreams_zlib.cpp:17]: In principle that should work (and would give you some log output, since `hello.z` gets dumped to `stdout`) - I'll take a look.

File: recipe/run_test.sh (hunk 1 above)
Comment (jakirkham) [reply recipe/run_test.sh]: Yep you're right. Did a bit more digging and it does seem Conda-Build should handle this correctly ( https://github.com/conda-forge/conda-forge.github.io/issues/1490#issuecomment-1097336276 )

File: recipe/run_test.sh [hunk 5]
```diff
@@ -0,0 +1,8 @@
...
+if [[ "${build_platform}" != "${target_platform}" ]]; then
+  exit 0
+fi
+
+# Test boost::iostreams zlib filter support
+cd test
+${CXX} -I$PREFIX/include -L$PREFIX/lib test_iostreams_zlib.cpp -lboost_iostreams && ./a.out
```
Comment (jakirkham) [inline recipe/run_test.sh:8]: Maybe we need to set the `rpath`? Mentioning since the macOS build fails with a library loading error.

```suggestion
${CXX} -I$PREFIX/include -L$PREFIX/lib -Wl,-rpath,$PREFIX/lib test_iostreams_zlib.cpp -lboost_iostreams && ./a.out
```

Comment (benmwebb) [reply recipe/run_test.sh:8]: Yes, I was just looking at that too. Your suggestion seems reasonable to me - let's try it.

File: recipe/run_test.sh (hunk 2 above)
Comment (jakirkham) [reply recipe/run_test.sh:1]:
```suggestion
# Skip compile tests if we are cross-compiling

set -xeou pipefail
```

File: recipe/run_test.bat (hunk 4 above)
Comment (jakirkham) [reply recipe/run_test.bat:1]:
```suggestion
:: Test boost::iostreams zlib filter support

@echo on
```

File: recipe/run_test.bat [hunk 6]
```diff
@@ -0,0 +1,7 @@
...
+cd test
```
Comment (jakirkham) [inline recipe/run_test.bat:2]:
```suggestion
cd test
if errorlevel 1 exit 1

```

**Review by jakirkham — COMMENTED** [review]
A few suggestions to get more info from the `run_test.*` scripts

File: recipe/run_test.sh (hunk 1 above)
Comment (jakirkham) [reply recipe/run_test.sh]: Ah sorry I misinterpreted and thought you already knew that 😂

Yeah they should work together, but as noted in the issue there may have been edge cases where that wasn't true.

Should add normally the commands are echoed (as in [this CI build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=489010&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=17342 )), but it looks like that output is suppressed when adding them to the end of `run_test.*` scripts. Maybe this is leading to confusion about whether they are being run?

Added some options to the `run_test.*` scripts, which should hopefully make it clearer that those tests are being run.

Perhaps part of the answer is Conda-Build should run `run_test.*` with these verbose options included?

File: recipe/run_test.bat [hunk 7]
```diff
@@ -0,0 +1,11 @@
+:: Test boost::iostreams zlib filter support
+
+@echo on
+cd test
```
Comment (jakirkham) [inline recipe/run_test.bat:4]:
```suggestion
@echo on

cd test
```

File: recipe/run_test.sh (hunk 1 above)
Comment (jakirkham) [reply recipe/run_test.sh]: Hmm...so I do see the compiler test running [here]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=491401&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=17405 ). Though am not seeing the file tests afterwards. Maybe I'm still missing something?

Comment (jakirkham) [reply recipe/run_test.sh]: Ok think I figured out what is going on here. Filed issue ( https://github.com/conda/conda-build/issues/4427 ).

**Comment by jakirkham** [comment]
Thanks Ben! 😄

Let's get this in. Will follow up on the Conda-Build issue separately.
